### ISSUE TITLE
Security Onion 

### ISSUE THREAD

**Issue by rammyfzl** [AlpenFlizzer/janus-gateway-docker#1]
Hi there Sascha!

My apologies for posting this under your Janus project, I was unsure of how else to reach out. Ive noticed you posted a very detailed issue within the Security Onion Discussions section. I see that you have real time monitoring enabled on your build. This is something I have been struggling with on my evaluation install. I plan to move to standalone and then distributed, but wanted to get everything up and running before moving on to the next. Do you mind lobbing a few pointers or suggestions my way? 

I'm running SO v2.3.21 on top of an ESXi host, and have confirmed that I can see network traffic from the SO host. I have also been able to replay a pcap with malicious traffic via so-import-pcap. From this, though I was able to have alerts generated in Hunt, I am not able to see the related PCAP. Not sure if this is relevant/related, just thought I would mention it. 

Thanks for any tips!

**Comment by rammyfzl** [comment]
Hello?

**Comment by boecks** [comment]
Sorry, this was probably not the best way to contact me. It just happened by accident, that I saw your question here... :-D 

I am not an expert on this whole topic at all, I just had to do this stuff in terms of an university course mand my Masters Thesis.

However, what I have learned (hard!) ist that you want to have enough RAM left for your VM. To be honest, everything went smooth using the instructions from the SO documentation for the setup process. I had SO monitor a small Lab Network via a second NIC, which was connected to a Switch that did mirror all traffic to this port - which would obviously be a bottleneck in a productive setup. What I could not manage, was to get Suricata alerts from a malicious PCAP that I replayed from a host in my Lab Network. If you use so-import-pcap, you have to filter for the correct time, when the PCAP was actually created!

I am afraid I can't help you further. Maybe it is of value for you to know, that I have also used RockNSM where there were no such problems with the PCAP replay like in SO. SELKS might also be interesting for you, but this depends on your needs.

Best, AF

**Comment by boecks** [comment]
Issue not related to repo
